import os

from dotenv import load_dotenv

load_dotenv()

AZURE_OPENAI_API_KEY = os.environ["AZURE_OPENAI_API_KEY"]
AZURE_OPENAI_ENDPOINT = os.environ["AZURE_OPENAI_ENDPOINT"]
AZURE_OPENAI_EMBEDDINGS_MODEL = os.environ["AZURE_OPENAI_EMBEDDINGS_MODEL"]
AZURE_OPENAI_CHAT_MODEL = os.environ["AZURE_OPENAI_CHAT_MODEL"]
AZURE_OPENAI_API_VERSION = os.environ["AZURE_OPENAI_API_VERSION"]
CHROMA_PATH = os.getenv("CHROMA_PATH", "chroma")
CHROMA_COLLECTION_NAME = os.getenv("COLLECTION_NAME", "local-rag")
